[deps]
AdvancedHMC = "0bf59076-c3b1-5ca4-86bd-e02cd72cde3d"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DynamicHMC = "bbc10e6e-7c05-544b-b16e-64fede858acb"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LogDensityProblems = "6fdf6af0-433a-55f7-b3ed-c6c6e0b8df7c"
LogDensityProblemsAD = "996a588d-648d-4e1f-a8f0-a84b347e47b1"
Pathfinder = "b1d3bc72-d0e7-4279-b92f-7fa5d6d2d454"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
TransformVariables = "84d833dd-6860-57f9-a1a7-6da5db126cff"
TransformedLogDensities = "f9bc47f6-f3f8-4f3b-ab21-f8bc73906f26"
Turing = "fce5fe82-541a-59a6-adf8-730c64b5f9a0"

[compat]
AdvancedHMC = "0.3, 0.4"
Documenter = "0.27"
DynamicHMC = "3"
ForwardDiff = "0.10"
LogDensityProblems = "1, 2"
LogDensityProblemsAD = "1, 2"
Pathfinder = "0.5"
StatsFuns = "0.9, 1"
StatsPlots = "0.14, 0.15"
TransformVariables = "0.6, 0.7"
TransformedLogDensities = "1"
Turing = "0.21, 0.22, 0.23"
